global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "gateway-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "192.168.35.139:80" ]

  - job_name: "identity-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "192.168.35.190:8080" ]
